//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWebClient.HelloWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloWebService.HelloWebServiceSoap")]
    public interface HelloWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessage", ReplyAction="*")]
        HelloWebClient.HelloWebService.GetMessageResponse GetMessage(HelloWebClient.HelloWebService.GetMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloWebClient.HelloWebService.GetMessageResponse> GetMessageAsync(HelloWebClient.HelloWebService.GetMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddtwoNo", ReplyAction="*")]
        int AddtwoNo(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddtwoNo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddtwoNoAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubtractTwoNo", ReplyAction="*")]
        int SubtractTwoNo(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubtractTwoNo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubtractTwoNoAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MulTwoNo", ReplyAction="*")]
        int MulTwoNo(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MulTwoNo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MulTwoNoAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DivideTwoNo", ReplyAction="*")]
        int DivideTwoNo(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DivideTwoNo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DivideTwoNoAsync(int a, int b);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessage", Namespace="http://tempuri.org/", Order=0)]
        public HelloWebClient.HelloWebService.GetMessageRequestBody Body;
        
        public GetMessageRequest() {
        }
        
        public GetMessageRequest(HelloWebClient.HelloWebService.GetMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetMessageRequestBody() {
        }
        
        public GetMessageRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelloWebClient.HelloWebService.GetMessageResponseBody Body;
        
        public GetMessageResponse() {
        }
        
        public GetMessageResponse(HelloWebClient.HelloWebService.GetMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMessageResult;
        
        public GetMessageResponseBody() {
        }
        
        public GetMessageResponseBody(string GetMessageResult) {
            this.GetMessageResult = GetMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWebServiceSoapChannel : HelloWebClient.HelloWebService.HelloWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWebServiceSoapClient : System.ServiceModel.ClientBase<HelloWebClient.HelloWebService.HelloWebServiceSoap>, HelloWebClient.HelloWebService.HelloWebServiceSoap {
        
        public HelloWebServiceSoapClient() {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloWebClient.HelloWebService.GetMessageResponse HelloWebClient.HelloWebService.HelloWebServiceSoap.GetMessage(HelloWebClient.HelloWebService.GetMessageRequest request) {
            return base.Channel.GetMessage(request);
        }
        
        public string GetMessage(string name) {
            HelloWebClient.HelloWebService.GetMessageRequest inValue = new HelloWebClient.HelloWebService.GetMessageRequest();
            inValue.Body = new HelloWebClient.HelloWebService.GetMessageRequestBody();
            inValue.Body.name = name;
            HelloWebClient.HelloWebService.GetMessageResponse retVal = ((HelloWebClient.HelloWebService.HelloWebServiceSoap)(this)).GetMessage(inValue);
            return retVal.Body.GetMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloWebClient.HelloWebService.GetMessageResponse> HelloWebClient.HelloWebService.HelloWebServiceSoap.GetMessageAsync(HelloWebClient.HelloWebService.GetMessageRequest request) {
            return base.Channel.GetMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelloWebClient.HelloWebService.GetMessageResponse> GetMessageAsync(string name) {
            HelloWebClient.HelloWebService.GetMessageRequest inValue = new HelloWebClient.HelloWebService.GetMessageRequest();
            inValue.Body = new HelloWebClient.HelloWebService.GetMessageRequestBody();
            inValue.Body.name = name;
            return ((HelloWebClient.HelloWebService.HelloWebServiceSoap)(this)).GetMessageAsync(inValue);
        }
        
        public int AddtwoNo(int a, int b) {
            return base.Channel.AddtwoNo(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddtwoNoAsync(int a, int b) {
            return base.Channel.AddtwoNoAsync(a, b);
        }
        
        public int SubtractTwoNo(int a, int b) {
            return base.Channel.SubtractTwoNo(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SubtractTwoNoAsync(int a, int b) {
            return base.Channel.SubtractTwoNoAsync(a, b);
        }
        
        public int MulTwoNo(int a, int b) {
            return base.Channel.MulTwoNo(a, b);
        }
        
        public System.Threading.Tasks.Task<int> MulTwoNoAsync(int a, int b) {
            return base.Channel.MulTwoNoAsync(a, b);
        }
        
        public int DivideTwoNo(int a, int b) {
            return base.Channel.DivideTwoNo(a, b);
        }
        
        public System.Threading.Tasks.Task<int> DivideTwoNoAsync(int a, int b) {
            return base.Channel.DivideTwoNoAsync(a, b);
        }
    }
}
